---
server:
    install: '1'
    timezone: UTC
    locale: en_US.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: default, ip: 192.168.33.99, memory: '512', sharedfolder: ./, useVagrantCloud: '1', syncType: nfs }
apache:
    install: '1'
    docroot: /vagrant/html
    servername: pardna-dev
mysql:
    install: '1'
    root_password: '123'
    database: pardna
    user: user
    password: password
    dump: ''
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-common, php5-mysql, php5-curl]
xdebug:
    install: '1'
composer:
    install: '1'
adminer_add_apache_config: true
apache_conf_path: /etc/apache2
app_install_dir: /vagrant/app
