---
- hosts: all
  sudo: true
  vars_files:
    - vars/all.yml
  roles:
    - server
    - vagrant_local
    - nodejs
    - apache
    - mysql
    - php
    - composer
    - xdebug
    - adminer
    - app
